apiVersion: v1
data:
  APIM_SOLR_SSL_CERT: {{ include "apim-solr-crt" . | b64enc | quote }}
  APIM_TPS_SSL_CERT: {{ include "apim-tps-crt" . | b64enc | quote }}
  DATABASE_HOST: {{ required "Please fill in databaseHost in values.yaml" .Values.user.databaseHost | quote }}
  DATABASE_NAME: {{ include "portal-db-name" . | quote }}
  DATABASE_PASSWORD: {{ required "Please fill in databasePassword in values.yaml" .Values.user.databasePassword | quote }}
  DATABASE_PORT: {{ include "database-port" . | quote }}
  DATABASE_TYPE: {{ required "Please fill in databaseType in values.yaml" .Values.user.databaseType | quote }}
  DATABASE_USERNAME: {{ required "Please fill in databaseUsername in values.yaml" .Values.user.databaseUsername | quote }}
  DATALAKE_SSL_KEY: {{ include "apim-datalake" . | b64enc | quote }}
  DATALAKE_SSL_KEY_PASS: {{ required "Please fill in datalakeKeyPass in values.yaml" .Values.secrets.datalakeKeyPass | quote }}
  DSSG_SSL_KEY: {{ include "apim-dssg" . | b64enc | quote }}
  DSSG_SSL_KEY_PASS: {{ required "Please fill in dssgKeyPass in values.yaml" .Values.secrets.dssgKeyPass | quote }}
  NSS_SDB_USE_CACHE: "no"
  OTK_DATABASE_NAME: {{ include "otk-db-name" . | quote }}
  OTK_PORT: "443"
  PAPI_PASSWORD: {{ .Values.user.papiPassword | quote }}
  PAPI_USERNAME: {{ .Values.user.papiUsername | quote }}
  PORTAL_SUBDOMAIN: {{ required "Please fill in domain in values.yaml" .Values.user.domain | quote }}
  PORTAL_VERSION: {{ .Chart.AppVersion }}
  PSSG_PASSWORD: M2NlY2RhZTMyZDZkNWMyZGI3
  PSSG_SSL_KEY: {{ include "pssg-ssl" . | b64enc | quote }}
  PSSG_SSL_KEY_PASS: {{ required "Please fill in pssgSslKeyPass in values.yaml" .Values.secrets.pssgSslKeyPass | quote }}
  PSSG_USERNAME: admin
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.config.password | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.config.username | quote }}
  SSG_ADMIN_PASSWORD: M2NlY2RhZTMyZDZkNWMyZGI3
  SSG_ADMIN_USERNAME: admin
  SSG_CLUSTER_HOST: {{ include "tssg-public-host" . | quote }}
  SSG_JVM_HEAP: 4096m
  SSG_LICENSE: {{ include "portal-license" . | b64enc | quote }}
  SSG_PASSWORD: lh9M0SlIC8UHIBNwR/eQ5Z9V
  SSG_SSL_KEY: {{ include "apim-ssl" . | b64enc | quote }}
  SSG_SSL_KEY_PASS: {{ required "Please fill in apimSslKeyPass in values.yaml" .Values.secrets.apimSslKeyPass | quote }}
  SSG_USERNAME: admin
  TENANT_ID: {{ include "default-tenant-id" . | quote }}
  TSSG_PUBLIC_HOST: {{ include "tssg-public-host" . | quote }}
  TSSG_PUBLIC_PORT: "443"
kind: ConfigMap
metadata:
  labels:
    name: apim
  name: apim-config