{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: portal-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - secretName: dispatcher-tls
    hosts:
    - {{ include "get-ingress-hosts" . | quote }}
  rules:
  - host: {{ include "default-tenant-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: dispatcher
          servicePort: portal-https
  - host: {{ include "tssg-public-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: apim
          servicePort: {{ printf "%s-https" .Values.user.defaultTenantId | quote }}
  - host: {{ include "analytics-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: apim
          servicePort: {{ printf "%s-datalake" .Values.user.defaultTenantId | quote }}
  - host: {{ include "pssg-enroll-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: pssg
          servicePort: tssg-enroll
  - host: {{ include "pssg-sync-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: pssg
          servicePort: tssg-sync
  - host: {{ include "pssg-sso-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: apim
          servicePort: {{ printf "%s-sso" .Values.user.defaultTenantId | quote }}
  - host: {{ include "broker-host" . | quote }}
    http:
      paths:
      - backend:
          serviceName: apim
          servicePort: {{ printf "%s-broker" .Values.user.defaultTenantId | quote }}
{{- end }}
